//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class praca
    {
        public int id { get; set; }
        public int Id_pracownika { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> Data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia { get; set; }
        public string Czy_pracuje { get; set; }
    
        public virtual users users { get; set; }
    }
}
