//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_roles
    {
        public int id_user { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual users users { get; set; }
    }
}
