//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual user_roles user_roles { get; set; }
        public virtual praca praca { get; set; }
        public virtual wiadomosci wiadomosci { get; set; }
        public virtual zarobki zarobki { get; set; }
    }
}
