//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_wnioski
    {
        public int Id { get; set; }
        public int id_pracownika { get; set; }
        public int id_wniosku { get; set; }
        public System.DateTime Data_rozpoczecia { get; set; }
        public System.DateTime Data_zakonczenia { get; set; }
        public string Notka { get; set; }
        public Nullable<int> kwota { get; set; }
        public Nullable<bool> Status_Wniosku { get; set; }
        public int noti_c { get; set; }
    
        public virtual users users { get; set; }
        public virtual wnioski wnioski { get; set; }
    }
}
